apiVersion: v1
kind: Service
metadata:
  name: securenexus
  namespace: uat
  labels:
    app: securenexus
    environment: uat
spec:
  type: LoadBalancer
  selector:
    app: securenexus
    environment: uat
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
