apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    app.kubernetes.io/part-of: securenexus
    app: securenexus
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    app.kubernetes.io/part-of: securenexus
    app: securenexus
    environment: uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    app.kubernetes.io/part-of: securenexus
    app: securenexus
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    app.kubernetes.io/part-of: securenexus
    app: securenexus
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: securenexus
    app: securenexus
