apiVersion: v1
kind: ServiceAccount
metadata:
  name: securenexus
  namespace: staging
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/securenexus-staging
  labels:
    app.kubernetes.io/name: securenexus
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: securenexus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: securenexus
  namespace: uat
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/securenexus-uat
  labels:
    app.kubernetes.io/name: securenexus
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: securenexus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: securenexus
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/securenexus-production
  labels:
    app.kubernetes.io/name: securenexus
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: securenexus
